name: mobx_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/caipirinha.jpg
    - assets/images/chicken-salad.png
    - assets/images/chicken-tender.png
    - assets/images/chicken-tortilla.png
    - assets/images/cold-noodles.png
    - assets/images/coxinhas.png
    - assets/images/fish-n-salsa.png
    - assets/images/hamburger-ink.png
    - assets/images/pamonha.png
    - assets/images/penne-au-sugo.png
    - assets/images/rice-n-beans.jpg
    - assets/images/shrimp-n-rice.png
    - assets/images/spagetti.png
    - assets/images/steak-veggies.png
    - assets/images/steak.png
    - assets/images/tapioca-taco.jpg
    - assets/images/lasagna-bolognese.jpg
    - assets/images/visa.png